[package]
name = "pages"
description = "Description pending"
authors = ["Nya (https://git.smgames.club/mrrp)"]
version = "0.1.0"
license = "MIT License"
edition = "2024"

[dependencies]
actix-web = "4"
log = "0.4"
fern = "0.7"