name = "SMGames Pages" # or whatever else
description = "Page system for SMGames"
urls = "https://pages.smgames.club"
pages_urls = ["https://pages.smgames.club"]
default_user = "admin"
port = 8080

# Optional
[ui]
# Optional: Specifies a directory that contains asset files
# These files can use Jinga templates
# Built in files will take priority
#overrides = "./templates"

[upstream]
# Optional: Defaults to Forgejo
type = "forgejo"
# Optional: Determines how it should get data from the upstream
# Leave blank for automatic
method = "direct"
# Optional: Identifies where to find the repositories for the pages
# Defaults to codeberg.org
url = "https://git.smgames.club"
# Optional: Specifies what branch should be the default when accessing a page
# Leave blank for "page"
default_branch = "pages"
# Optional: Specifies what branches are allowed to be shown
# If not specified, any branch will be accepted
branches = ["pages"]
#token = "my-auth-token"

[security]
#whitelist = { owner = "*", repo = "*" }
#blacklist = { owner = "*", repo = "*" }
#disallow-files = "*"