name = "Pageshelf" # or whatever else
description = "A free and open source Pages system, written in the Rust language."
urls = "http://localhost"
#pages_urls = ["http://localhost/"]
default_user = "mrrp"
port = 8080
allow_domains = false

# Optional
[ui]
# Optional: Specifies a directory that contains asset files
# These files can use Jinja templates
# Built in files will take priority
#overrides = "./templates"

[upstream]
# Optional: Defaults to Forgejo
type = "forgejo"
# Optional: Determines how it should get data from the upstream
# Leave blank for automatic
method = "direct"
# Optional: Identifies where to find the repositories for the pages
url = "https://git.smgames.club"
# Optional: Specifies what branch should be the default when accessing a page
# Leave blank for "page"
default_branch = "pages"
# Optional: Specifies what branches are allowed to be shown
# If not specified, any branch will be accepted
branches = ["pages"]
#token = "my-auth-token"

[security]
#whitelist = { owner = "*", repo = "*", file = "*" }
#blacklist = { owner = "*", repo = "*", file = "*" }
show_private = false

[redis]
enabled = true
ttl = 480