[package]
name = "pageshelf-provider-cache-redis"
description = "A free and open source Pages server, written in Rust - Provider for Forgejo"
authors = ["V. D. <nyamrrp@proton.me>"]
version = "0.2.0"
license = "MIT License"
edition = "2024"
publish = false

[dependencies]
pageshelf-core = { path = "../../core" }
tracing = { version = "0.1", features = [], default-features = false }
url = { version = "2.5.7", features = ["serde"] }
serde = "1"
color-eyre = { version = "0.6", default-features = false }
tokio = { version = "1", features = ["sync"] }
config = "0.15"
redis = {version = "0.32", features = ["aio", "tokio-comp", "cache-aio"] }

[dev-dependencies]
pageshelf-test-utils = { path = "../../test-utils" }
testcontainers = "0.25"