on:
  push:
    branches:
      - "canary"
  workflow_dispatch:

jobs:
  build-publish:
    name: 🐋 Build and Publish (Canary)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build Inventory Image
        run: |
          docker build . --tag ghcr.io/${{github.actor}}/pageshelf:canary
          docker push ghcr.io/${{github.actor}}/pageshelf:canary